// E-Waste Hardware Reclaimer - Electronics Salvage Assistant
// Database of 200+ Electronic Components with Salvage metadata

const COMPONENT_DATABASE = [
  // --- PASSIVES: RESISTORS ---
  {
    names: ["carbon film resistor", "resistor", "axial resistor", "fixed resistor"],
    category: "passive",
    subcategory: "resistor",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.01,
    repurposeIdeas: ["Current limiting for LEDs", "Pull-up/pull-down resistors", "Voltage dividers", "Breadboard prototyping"],
    safetyNotes: "Safe to handle. Standard passive component.",
    recyclingInfo: "Standard e-waste recycling. Metal leads contain tin/copper."
  },
  {
    names: ["smd resistor", "chip resistor", "0805 resistor", "0603 resistor", "1206 resistor"],
    category: "passive",
    subcategory: "resistor",
    package: "smd",
    classification: "recyclable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.005,
    repurposeIdeas: ["Compact custom PCBs", "Repairing consumer electronics", "High-frequency circuits"],
    safetyNotes: "Extremely small, easily lost or inhaled. Handle with tweezers.",
    recyclingInfo: "Standard e-waste recycling. Low reclaim value due to tiny size."
  },
  {
    names: ["potentiometer", "variable resistor", "pot", "trimmer potentiometer", "trimpot"],
    category: "passive",
    subcategory: "resistor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.40,
    repurposeIdeas: ["Volume/gain controllers", "Speed regulators", "Adjustable voltage references", "Custom synthesizer controllers"],
    safetyNotes: "Check shaft rotation. If gritty or stiff, clean with contact cleaner (deoxIT).",
    recyclingInfo: "High metal content. Salvage highly recommended."
  },
  {
    names: ["power resistor", "cement resistor", "wirewound resistor", "ceramic resistor"],
    category: "passive",
    subcategory: "resistor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.25,
    repurposeIdeas: ["Dummy load testing for power supplies", "Heating elements", "Current sensing in high power applications"],
    safetyNotes: "Can get extremely hot during operation. Allow to cool.",
    recyclingInfo: "Ceramic casing is inert. Inside is resistive wire (nichrome)."
  },
  {
    names: ["varistor", "mov", "metal oxide varistor", "surge protector"],
    category: "passive",
    subcategory: "resistor",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.08,
    repurposeIdeas: ["Input surge protection for custom mains projects"],
    safetyNotes: "Often fails catastrophically (burns or cracks) when absorbing a surge. Visually inspect before reuse.",
    recyclingInfo: "Standard e-waste recycling."
  },
  {
    names: ["thermistor", "ntc thermistor", "ptc thermistor", "temperature sensor resistor"],
    category: "passive",
    subcategory: "resistor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.15,
    repurposeIdeas: ["DIY weather stations", "Over-temperature shutdown circuits", "Battery charging monitors"],
    safetyNotes: "Fragile glass beads or ceramic coating. Avoid bending leads too close to the body.",
    recyclingInfo: "Standard e-waste."
  },
  {
    names: ["ldr", "light dependent resistor", "photoresistor", "cadmium sulfide cell", "cds cell"],
    category: "passive",
    subcategory: "resistor",
    package: "through-hole",
    classification: "hazardous",
    desolderDifficulty: 1,
    hazards: ["Toxic heavy metal exposure if broken"],
    hazardMaterials: ["cadmium"],
    estimatedValue: 0.12,
    repurposeIdeas: ["Light-activated switches", "Night lights", "Solar tracker projects"],
    safetyNotes: "Contains Cadmium Sulfide (CdS). Do not crush, burn, or ingest. Reusing is fine if encapsulated and unbroken.",
    recyclingInfo: "Must be disposed of in hazardous e-waste due to heavy metal content (Cadmium)."
  },

  // --- PASSIVES: CAPACITORS ---
  {
    names: ["electrolytic capacitor", "aluminum electrolytic capacitor", "radial capacitor", "can capacitor"],
    category: "passive",
    subcategory: "capacitor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: ["Potential electrolyte leak/explosion if old or reverse-biased"],
    hazardMaterials: [],
    estimatedValue: 0.10,
    repurposeIdeas: ["Power supply decoupling", "Audio circuit filtering", "Energy storage buffer"],
    safetyNotes: "Watch for bulging tops or white/crusty residue (signs of leakage). Discharge before desoldering. Polarity sensitive!",
    recyclingInfo: "Standard e-waste. Aluminum casing is recyclable."
  },
  {
    names: ["tantalum capacitor", "tantalum bead capacitor"],
    category: "passive",
    subcategory: "capacitor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: ["Violent short-circuit failure mode (can catch fire)"],
    hazardMaterials: ["tantalum"],
    estimatedValue: 0.30,
    repurposeIdeas: ["Precision timing circuits", "High-reliability decoupling", "Low-noise audio filtering"],
    safetyNotes: "Tantalum capacitors fail short-circuit with flame. Match voltage rating strictly (keep 50% safety margin). Polarity sensitive!",
    recyclingInfo: "Contains valuable Tantalum, a conflict mineral. Salvage/recycle highly recommended."
  },
  {
    names: ["ceramic capacitor", "ceramic disc capacitor", "monolithic capacitor"],
    category: "passive",
    subcategory: "capacitor",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.02,
    repurposeIdeas: ["RF bypass", "Decoupling high frequency noise", "Debouncing buttons"],
    safetyNotes: "Brittle, can crack if bent or overheated during desoldering.",
    recyclingInfo: "Standard e-waste. Low material salvage value."
  },
  {
    names: ["smd ceramic capacitor", "mlcc", "smd capacitor", "0805 capacitor", "0603 capacitor"],
    category: "passive",
    subcategory: "capacitor",
    package: "smd",
    classification: "recyclable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.005,
    repurposeIdeas: ["Compact high-frequency filtering", "Custom PCB prototypes"],
    safetyNotes: "Susceptible to micro-cracking from thermal shock during desoldering, leading to shorts.",
    recyclingInfo: "Standard e-waste. Very low salvage value individually."
  },
  {
    names: ["film capacitor", "polyester film capacitor", "mylar capacitor", "polypropylene capacitor"],
    category: "passive",
    subcategory: "capacitor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.18,
    repurposeIdeas: ["Crossover networks in audio speakers", "Mains AC noise filters", "Guitar tone circuits"],
    safetyNotes: "High-voltage film caps can hold charge for a long time. Discharge before handling.",
    recyclingInfo: "Standard e-waste."
  },
  {
    names: ["supercapacitor", "ultracapacitor", "gold capacitor", "double layer capacitor"],
    category: "passive",
    subcategory: "capacitor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: ["High short-circuit current / sparks risk"],
    hazardMaterials: [],
    estimatedValue: 1.50,
    repurposeIdeas: ["Battery-free memory backup power", "Solar energy storage", "Quick-charge toys", "Microcontroller keep-alive supply"],
    safetyNotes: "Can discharge extreme current if shorted, melting wires or creating burns. Fully discharge before working.",
    recyclingInfo: "Contains activated carbon and organic electrolytes. Treat as special e-waste if leaking."
  },
  {
    names: ["old pcb capacitor", "pcb oil capacitor", "vintage oil capacitor", "askarel capacitor"],
    category: "passive",
    subcategory: "capacitor",
    package: "through-hole",
    classification: "hazardous",
    desolderDifficulty: 3,
    hazards: ["Highly toxic, carcinogenic PCB oil exposure if leaking"],
    hazardMaterials: ["pcbs"],
    estimatedValue: 0.0,
    repurposeIdeas: ["Do NOT reuse under any circumstances."],
    safetyNotes: "Pre-1979 heavy duty oil-filled capacitors may contain PCBs (Polychlorinated Biphenyls). Highly carcinogenic, toxic to skin. Do not touch if leaking. Bag immediately.",
    recyclingInfo: "Must be disposed of as hazardous chemical waste. Do not place in general e-waste."
  },

  // --- PASSIVES: INDUCTORS & TRANSFORMERS ---
  {
    names: ["toroid inductor", "ring inductor", "toroidal choke"],
    category: "passive",
    subcategory: "inductor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.35,
    repurposeIdeas: ["Switching regulator filters", "DIY radio antennas", "EMI filtering in custom power supplies"],
    safetyNotes: "The copper wire can be unwound and harvested for custom windings.",
    recyclingInfo: "High value for copper and ferrite/iron reclamation."
  },
  {
    names: ["drum core inductor", "radial inductor", "axial inductor"],
    category: "passive",
    subcategory: "inductor",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.05,
    repurposeIdeas: ["Buck/boost converter circuits", "Filter networks"],
    safetyNotes: "Often very small and brittle ferrite core.",
    recyclingInfo: "Ferrite core and thin copper wire. Recyclable."
  },
  {
    names: ["power transformer", "mains transformer", "audio transformer", "ei transformer"],
    category: "passive",
    subcategory: "transformer",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 4,
    hazards: ["High weight and mechanical stress during desoldering"],
    hazardMaterials: [],
    estimatedValue: 2.50,
    repurposeIdeas: ["Linear bench power supplies", "Audio tube amplifier outputs", "Isolation transformers"],
    safetyNotes: "Very heavy. Iron laminations can have sharp edges. Test windings for continuity and insulation resistance before reuse.",
    recyclingInfo: "Excellent recycling value due to heavy copper windings and steel core."
  },
  {
    names: ["flyback transformer", "line output transformer", "lopt"],
    category: "passive",
    subcategory: "transformer",
    package: "through-hole",
    classification: "hazardous",
    desolderDifficulty: 4,
    hazards: ["Extreme high voltage shock hazard, potential toxic dust inside older units"],
    hazardMaterials: [],
    estimatedValue: 1.00,
    repurposeIdeas: ["High voltage experimentation (Tesla coils, Marx generators, Jacob's ladders)"],
    safetyNotes: "Can retain hazardous high voltage charge in its built-in diodes/capacitors for days. Discharge terminal. Internal resin potting may contain hazardous flame retardants.",
    recyclingInfo: "Specialized e-waste facility. Difficult to recycle due to epoxy potting."
  },

  // --- SEMICONDUCTORS: DIODES ---
  {
    names: ["rectifier diode", "1n4007", "1n5408", "silicon diode"],
    category: "semiconductor",
    subcategory: "diode",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.02,
    repurposeIdeas: ["AC/DC rectification bridge", "Reverse polarity protection", "Inductive flyback clamping"],
    safetyNotes: "Check polarity (cathode band). Easy to desolder and reuse.",
    recyclingInfo: "Silicon wafer, copper leads. Standard e-waste."
  },
  {
    names: ["schottky diode", "1n5819", "fast diode", "barrier diode"],
    category: "semiconductor",
    subcategory: "diode",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.08,
    repurposeIdeas: ["High efficiency solar panel bypass", "High frequency switching regulators", "Low voltage drop protection"],
    safetyNotes: "Very low forward voltage drop. Excellent for power conservation projects.",
    recyclingInfo: "Standard e-waste."
  },
  {
    names: ["zener diode", "voltage regulator diode"],
    category: "semiconductor",
    subcategory: "diode",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.03,
    repurposeIdeas: ["Voltage clamping", "Simple voltage references", "Over-voltage protection gates"],
    safetyNotes: "Markings indicate breakdown voltage. Test before reuse.",
    recyclingInfo: "Standard e-waste."
  },
  {
    names: ["led", "light emitting diode", "5mm led", "3mm led"],
    category: "semiconductor",
    subcategory: "diode",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.05,
    repurposeIdeas: ["Indicator lights", "Custom flashlights", "Optical isolation projects", "Creative model lighting"],
    safetyNotes: "Avoid overheating leads while desoldering, as it can destroy the internal junction.",
    recyclingInfo: "Gallium, arsenic, or phosphorus compounds in tiny amounts. Standard e-waste."
  },
  {
    names: ["bridge rectifier", "diode bridge", "rectifier module"],
    category: "semiconductor",
    subcategory: "diode",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.35,
    repurposeIdeas: ["Heavy duty AC to DC conversion", "Wind turbine output rectification"],
    safetyNotes: "Often mounted on heat sinks. Requires high heat to desolder thick pins.",
    recyclingInfo: "Contains heavy copper heatsink interface. Good reclaim value."
  },

  // --- SEMICONDUCTORS: TRANSISTORS ---
  {
    names: ["mosfet", "power mosfet", "n-channel mosfet", "p-channel mosfet", "irf540", "irfz44n"],
    category: "semiconductor",
    subcategory: "transistor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.45,
    repurposeIdeas: ["PWM motor speed control", "High current LED strip switching", "DC-AC power inverters", "Solid state relays"],
    safetyNotes: "Gate is highly sensitive to Electrostatic Discharge (ESD). Short the pins together while handling.",
    recyclingInfo: "Copper tab (often tin-plated). High utility value."
  },
  {
    names: ["bjt transistor", "npn transistor", "pnp transistor", "2n2222", "bc547", "small signal transistor"],
    category: "semiconductor",
    subcategory: "transistor",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.03,
    repurposeIdeas: ["Small signal amplification", "Relay drivers", "Logic gates", "Sensor pre-amps"],
    safetyNotes: "Confirm pinout (Emitter-Base-Collector) since patterns vary (TO-92 packages).",
    recyclingInfo: "Standard silicon/copper."
  },
  {
    names: ["power bjt", "power transistor", "tip31", "tip3055", "to-3 transistor", "metal can transistor"],
    category: "semiconductor",
    subcategory: "transistor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 3,
    hazards: ["Potential toxic Beryllium Oxide in vintage RF power transistors"],
    hazardMaterials: ["beryllium"],
    estimatedValue: 0.60,
    repurposeIdeas: ["Linear audio power amplifiers", "DIY linear lab power supplies", "Heating controller switch"],
    safetyNotes: "WARNING: Vintage metal-can or RF power transistors (especially white ceramic packages) can contain Beryllium Oxide (BeO) inside. Do not scratch, break, or file the internal ceramic layer.",
    recyclingInfo: "Metal casing is copper/iron. Dispose as hazardous if containing BeO."
  },
  {
    names: ["igbt", "insulated gate bipolar transistor", "induction cooker transistor"],
    category: "semiconductor",
    subcategory: "transistor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 1.20,
    repurposeIdeas: ["High voltage switching", "Coilgun controllers", "DIY induction heaters", "EV motor drives"],
    safetyNotes: "High voltage capability. Always verify with component tester prior to load test.",
    recyclingInfo: "High-grade copper backing tab. Recyclable."
  },

  // --- INTEGRATED CIRCUITS ---
  {
    names: ["microcontroller", "mcu", "atmega328p", "pic microcontroller", "esp32 chip", "stm32 chip"],
    category: "semiconductor",
    subcategory: "ic",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 1.50,
    repurposeIdeas: ["Brain of custom IoT nodes", "Arduino-compatible hardware projects", "Automation sensors", "Smart home devices"],
    safetyNotes: "Desolder carefully using solder wick or a vacuum desoldering pump. Use an IC socket for the salvaged chip.",
    recyclingInfo: "Standard silicon wafer, gold wire bonds inside. Standard e-waste."
  },
  {
    names: ["op-amp", "operational amplifier", "lm358", "ua741", "ne5532", "tl072"],
    category: "semiconductor",
    subcategory: "ic",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.25,
    repurposeIdeas: ["Audio preamplifiers", "Active audio filters", "Sensor signal conditioning", "Comparator circuits"],
    safetyNotes: "Look up pinouts. Check for thermal discoloration which indicates chip damage.",
    recyclingInfo: "Standard e-waste."
  },
  {
    names: ["555 timer", "ne555", "timer ic"],
    category: "semiconductor",
    subcategory: "ic",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.15,
    repurposeIdeas: ["Astable multivibrator clock source", "LED blinkers", "PWM controllers", "Audible alarms/synths"],
    safetyNotes: "One of the most versatile ICs ever made. Very robust, highly recommended to salvage.",
    recyclingInfo: "Standard e-waste."
  },
  {
    names: ["linear voltage regulator", "7805", "7812", "lm317", "ams1117", "buck regulator ic"],
    category: "semiconductor",
    subcategory: "ic",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.20,
    repurposeIdeas: ["5V or 12V voltage regulators for microcontrollers", "Variable bench supply outputs", "Noise-free analog supply stages"],
    safetyNotes: "Linear regulators drop excess voltage as heat. Ensure proper heatsinking on reuse.",
    recyclingInfo: "Contains copper tab. Standard e-waste."
  },
  {
    names: ["optocoupler", "optoisolator", "pc817", "moc3021"],
    category: "semiconductor",
    subcategory: "ic",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.12,
    repurposeIdeas: ["Galvanic isolation between high and low voltage circuits", "Safe microcontroller interfacing with relays"],
    safetyNotes: "Pins are electrically isolated. Check input LED status using a diode tester.",
    recyclingInfo: "Standard e-waste."
  },
  {
    names: ["logic gate ic", "74hc08", "74hc00", "74series", "4000series", "cmos gate", "ttl gate"],
    category: "semiconductor",
    subcategory: "ic",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.10,
    repurposeIdeas: ["Custom hardware logic (AND, NAND, OR, XOR)", "Learning digital logic principles", "Extending MCU pins"],
    safetyNotes: "CMOS chips are sensitive to static. Handle pins carefully.",
    recyclingInfo: "Standard e-waste."
  },
  {
    names: ["flash memory", "eeprom", "nor flash", "nand flash", "bios chip", "24c02", "w25q64"],
    category: "semiconductor",
    subcategory: "ic",
    package: "smd",
    classification: "salvageable",
    desolderDifficulty: 4,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.40,
    repurposeIdeas: ["Storing sensor data logs", "Custom wavetable synthesizer audio data", "Microcontroller configuration storage"],
    safetyNotes: "Requires SPI or I2C reader to verify/wipe. Desoldering SMD flash requires a hot air rework station.",
    recyclingInfo: "Silicon wafer, gold wire bonds."
  },
  {
    names: ["ram chip", "sram", "dram", "sdram"],
    category: "semiconductor",
    subcategory: "ic",
    package: "smd",
    classification: "recyclable",
    desolderDifficulty: 4,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.15,
    repurposeIdeas: ["Hard to reuse due to complex high-speed memory buses, but good for gold/silicon scrap scrap value."],
    safetyNotes: "Solder pads are delicate. Often high pin counts.",
    recyclingInfo: "High gold wire content inside. Highly sought by gold refiners."
  },
  {
    names: ["cpu", "microprocessor", "intel cpu", "amd cpu", "arm processor"],
    category: "semiconductor",
    subcategory: "ic",
    package: "bga",
    classification: "salvageable",
    desolderDifficulty: 5,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 5.00,
    repurposeIdeas: ["Custom embedded Linux boards (advanced)", "Collectibles/keychains", "Gold scrap recovery"],
    safetyNotes: "Highly sensitive to heat damage. BGA packages require professional reballing and reflow to reuse.",
    recyclingInfo: "Very high gold/silver content. Send to high-value e-waste refiners."
  },

  // --- ELECTROMECHANICAL: RELAYS & SWITCHES ---
  {
    names: ["relay", "spdt relay", "12v relay", "5v relay", "signal relay", "mechanical relay"],
    category: "electromechanical",
    subcategory: "relay",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.50,
    repurposeIdeas: ["High-power AC load switching", "Microcontroller-based home automation", "Smart outlets"],
    safetyNotes: "Listen for the physical click. Test coil resistance and contact continuity. Switch contacts can wear out over time.",
    recyclingInfo: "High copper coil and silver contact content. Excellent for recycling."
  },
  {
    names: ["solid state relay", "ssr"],
    category: "electromechanical",
    subcategory: "relay",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 2.00,
    repurposeIdeas: ["Silent AC power switching", "PID heating controllers", "High-speed cycle load switching"],
    safetyNotes: "SSRs don't have mechanical wear but can fail shorted. Always heat sink properly when switching high currents.",
    recyclingInfo: "Contains semiconductor junction on ceramic substrate. Standard e-waste."
  },
  {
    names: ["tactile switch", "momentary switch", "push button", "micro switch"],
    category: "electromechanical",
    subcategory: "switch",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.08,
    repurposeIdeas: ["User interface buttons for custom projects", "Reset switches on prototype boards", "Debounced button input"],
    safetyNotes: "Very cheap but highly useful. Check button response using a multimeter (continuity mode).",
    recyclingInfo: "Plastic and metal plating. Standard e-waste."
  },
  {
    names: ["toggle switch", "rocker switch", "slide switch", "power switch"],
    category: "electromechanical",
    subcategory: "switch",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.60,
    repurposeIdeas: ["Power controls", "Mode toggles in projects", "Custom control panels"],
    safetyNotes: "Check current/voltage rating stamped on switch body before using on mains AC.",
    recyclingInfo: "High brass/copper content. Good recycling value."
  },
  {
    names: ["dip switch", "piano switch"],
    category: "electromechanical",
    subcategory: "switch",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.25,
    repurposeIdeas: ["Address configuration in multi-node sensor networks", "Option setting switch blocks"],
    safetyNotes: "Small sliding pins are delicate.",
    recyclingInfo: "Plastic body, gold-plated contacts. Standard e-waste."
  },
  {
    names: ["mercury switch", "tilt switch", "mercury tilt sensor"],
    category: "electromechanical",
    subcategory: "switch",
    package: "through-hole",
    classification: "hazardous",
    desolderDifficulty: 2,
    hazards: ["Extreme mercury poisoning hazard if glass bulb ruptures"],
    hazardMaterials: ["mercury"],
    estimatedValue: 0.0,
    repurposeIdeas: ["Do NOT reuse. Replace with modern ball-bearing or accelerometer tilt sensors."],
    safetyNotes: "Contains highly toxic liquid Mercury (Hg) inside a glass bulb. Do NOT break, desolder, or drop. If found on a board, clip the leads with pliers rather than desoldering to avoid heating the glass bulb.",
    recyclingInfo: "Must be separated and disposed of at a specialized toxic waste drop-off. Never place in standard bins."
  },

  // --- CONNECTORS ---
  {
    names: ["usb port", "usb-c connector", "micro usb port", "usb-b port"],
    category: "connector",
    subcategory: "port",
    package: "smd",
    classification: "salvageable",
    desolderDifficulty: 4,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.30,
    repurposeIdeas: ["Adding USB power input to custom projects", "Making custom chargers", "Repairing broken charging ports"],
    safetyNotes: "Tiny SMD data pins require fine soldering. The structural tabs are large through-holes that act as heatsinks.",
    recyclingInfo: "Contains gold plating on contact pins."
  },
  {
    names: ["barrel jack", "dc jack", "power socket"],
    category: "connector",
    subcategory: "port",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.20,
    repurposeIdeas: ["External wall-wart power input for custom projects", "Standardizing power connectors"],
    safetyNotes: "Standard size is usually 2.1mm or 2.5mm inner pin. Measure with a plug to verify.",
    recyclingInfo: "Metal contacts, plastic housing. Standard e-waste."
  },
  {
    names: ["audio jack", "3.5mm jack", "headphone jack", "trs jack"],
    category: "connector",
    subcategory: "port",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.15,
    repurposeIdeas: ["Audio input/output jacks on DIY synthesizers", "Trigger signals", "Serial debugging connections"],
    safetyNotes: "Contacts can become loose. Test retention force and electrical contact before mounting.",
    recyclingInfo: "Nickel/copper plating. Recyclable."
  },
  {
    names: ["header pins", "pin headers", "dupont connector", "male headers"],
    category: "connector",
    subcategory: "header",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.05,
    repurposeIdeas: ["Prototyping boards", "Breadboard hookups", "Microcontroller programming headers"],
    safetyNotes: "Pull the plastic spacer off to desolder pins individually if desoldering the whole block is too difficult.",
    recyclingInfo: "Usually gold-flash plated brass pins. High recyclability."
  },
  {
    names: ["screw terminal block", "phoenix connector"],
    category: "connector",
    subcategory: "terminal",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.35,
    repurposeIdeas: ["Secure high current wire-to-board connections", "Power supply inputs", "Relay board terminals"],
    safetyNotes: "Highly reusable. Ensure the screws are not rusted or stripped.",
    recyclingInfo: "Excellent copper/brass content inside plastic housing."
  },
  {
    names: ["rj45 port", "ethernet port", "lan connector"],
    category: "connector",
    subcategory: "port",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.15,
    repurposeIdeas: ["Custom wired networking projects", "Long distance sensor cables (Cat5/6 handles differential signals well)"],
    safetyNotes: "Often contains integrated magnetics (transformer) inside. Check datasheet if using for custom ethernet.",
    recyclingInfo: "Contains magnetic wire coils and gold pins."
  },

  // --- ELECTROMECHANICAL: MOTORS, BUZZERS, ETC. ---
  {
    names: ["dc motor", "toy motor", "brushed motor"],
    category: "electromechanical",
    subcategory: "motor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.80,
    repurposeIdeas: ["DIY fans", "Small robotics / RC cars", "Vibration haptic feedback", "Custom wind turbines"],
    safetyNotes: "Spin shaft manually. If smooth, check with a battery. Brushed motors degrade over time but are great for small tasks.",
    recyclingInfo: "High copper coil and neodymium/ferrite magnet value."
  },
  {
    names: ["stepper motor", "nema 17", "printer motor"],
    category: "electromechanical",
    subcategory: "motor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 3.50,
    repurposeIdeas: ["DIY 3D printers", "CNC routers", "Camera sliders", "Precision robotic arms"],
    safetyNotes: "Heavy copper winding, ball bearings, and permanent magnets. Test phases with a meter to ensure winding health.",
    recyclingInfo: "Very high recycling value (copper, steel, magnets)."
  },
  {
    names: ["buzzer", "piezo buzzer", "piezo element", "beeper"],
    category: "electromechanical",
    subcategory: "audio",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.12,
    repurposeIdeas: ["Audible alarms", "Custom retro game consoles", "Piezo contact microphones / guitar pickups"],
    safetyNotes: "Check if it is active (needs only DC voltage) or passive (needs AC/PWM square wave). Piezo crystals are fragile.",
    recyclingInfo: "Standard e-waste."
  },
  {
    names: ["speaker", "magnetic speaker", "toy speaker"],
    category: "electromechanical",
    subcategory: "audio",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.50,
    repurposeIdeas: ["Small amplifiers", "Voice synthesis output", "Custom radio projects"],
    safetyNotes: "Avoid puncturing the paper/mylar cone. Keep away from magnetic media.",
    recyclingInfo: "Excellent magnet and copper voice coil reclamation."
  },

  // --- SENSORS & TRANSDUCERS ---
  {
    names: ["accelerometer", "gyroscope", "mpu6050", "imu sensor"],
    category: "semiconductor",
    subcategory: "sensor",
    package: "smd",
    classification: "salvageable",
    desolderDifficulty: 4,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 1.20,
    repurposeIdeas: ["Self-balancing robots", "Motion controllers", "Tilt alarms", "RC flight stabilization"],
    safetyNotes: "Extremely sensitive MEMS silicon. Excess heat during rework can damage the internal micro-mechanisms.",
    recyclingInfo: "MEMS IC package. Standard e-waste."
  },
  {
    names: ["microphone", "electret microphone", "condenser mic", "mems microphone"],
    category: "electromechanical",
    subcategory: "audio",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.15,
    repurposeIdeas: ["Sound level detectors", "Voice recorders", "Hearing aids", "Clap switches"],
    safetyNotes: "Electret mics can lose charge/sensitivity over time or when exposed to excessive heat during desoldering.",
    recyclingInfo: "Aluminium housing. Recyclable."
  },
  {
    names: ["optocoupler sensor", "photointerrupter", "optical switch", "encoder sensor"],
    category: "semiconductor",
    subcategory: "sensor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.20,
    repurposeIdeas: ["Motor speed encoders", "Limit switches for 3D printers", "Rotary knobs"],
    safetyNotes: "Infrared LED on one side, phototransistor on the other. Align correctly on reuse.",
    recyclingInfo: "Standard e-waste."
  },

  // --- POWER SOURCES & BATTERIES ---
  {
    names: ["lithium battery", "lipo battery", "18650 cell", "lithium ion battery"],
    category: "power",
    subcategory: "battery",
    package: "through-hole",
    classification: "hazardous",
    desolderDifficulty: 4,
    hazards: ["Extreme fire/explosion risk if punctured, shorted, or overheated"],
    hazardMaterials: ["cobalt", "lithium"],
    estimatedValue: 2.00,
    repurposeIdeas: ["Power banks", "Portable electronics", "Solar system storage (requires balancing charger)"],
    safetyNotes: "NEVER desolder batteries with a hot iron directly onto terminals unless they are designed tabbed cells. Do not puncture or bend. Fire hazard. If bloated (swollen), do not use, recycle immediately.",
    recyclingInfo: "Must be disposed of at dedicated battery recycling collection points. Do not throw in household bins."
  },
  {
    names: ["nicd battery", "nickel cadmium battery", "rechargeable drill battery"],
    category: "power",
    subcategory: "battery",
    package: "through-hole",
    classification: "hazardous",
    desolderDifficulty: 2,
    hazards: ["Highly toxic Cadmium metal contamination risk"],
    hazardMaterials: ["cadmium"],
    estimatedValue: 0.0,
    repurposeIdeas: ["Do NOT reuse. Old chemistry with memory effect, prone to leaking."],
    safetyNotes: "Contains toxic Cadmium. Often leaks a white crystalline crust. Dispose immediately.",
    recyclingInfo: "Take to a battery recycling center. Toxic chemical hazard."
  },
  {
    names: ["coin cell holder", "cr2032 battery holder", "button battery clip"],
    category: "connector",
    subcategory: "power",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.15,
    repurposeIdeas: ["Adding RTC (Real Time Clock) backup power to MCU projects", "Small low-power wearable projects"],
    safetyNotes: "Ensure contacts are springy and not corroded. Remove the battery before desoldering.",
    recyclingInfo: "Nickel-plated brass. Highly recyclable."
  },
  {
    names: ["fuse", "glass fuse", "blade fuse", "ptc resettable fuse"],
    category: "power",
    subcategory: "protection",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 1,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.05,
    repurposeIdeas: ["Overcurrent protection for custom electronic builds"],
    safetyNotes: "Verify continuity to ensure fuse is not blown. Check current rating (e.g. 2A, 5A) printed on cap.",
    recyclingInfo: "Glass/metal or plastic/metal construction. Recyclable."
  },
  {
    names: ["heatsink", "aluminum heatsink"],
    category: "power",
    subcategory: "cooling",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.50,
    repurposeIdeas: ["Cooling custom power transistors, MOSFETs, and LEDs in DIY electronics"],
    safetyNotes: "Clean old thermal paste off using Isopropyl Alcohol (IPA) before reuse.",
    recyclingInfo: "High-grade aluminum. Excellent recycling scrap value."
  },

  // --- MISCELLANEOUS ---
  {
    names: ["quartz crystal", "crystal oscillator", "16mhz crystal", "8mhz crystal"],
    category: "passive",
    subcategory: "oscillator",
    package: "through-hole",
    classification: "recyclable",
    desolderDifficulty: 2,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.10,
    repurposeIdeas: ["Clock sources for microcontrollers and synthesizers"],
    safetyNotes: "Metal can packages. Resonant frequency (e.g., 16.000) is marked on the case.",
    recyclingInfo: "Quartz crystal inside iron/metal can. Standard e-waste."
  },
  {
    names: ["crt tube", "cathode ray tube", "old monitor screen"],
    category: "display",
    subcategory: "monitor",
    package: "other",
    classification: "hazardous",
    desolderDifficulty: 5,
    hazards: ["High vacuum implosion risk, high lead content glass, fatal residual high voltage"],
    hazardMaterials: ["lead"],
    estimatedValue: 0.0,
    repurposeIdeas: ["Do NOT reuse or dismantle unless trained. Safe only as vintage art pieces if kept sealed."],
    safetyNotes: "CRT displays contain up to 8 lbs of lead in the glass, and have a strong vacuum that can cause an implosion if cracked. High-voltage capacitors can store a fatal 25kV charge. Do not open.",
    recyclingInfo: "Requires professional hazardous electronic recycling."
  },
  {
    names: ["lcd screen", "character lcd", "16x2 lcd", "graphic lcd"],
    category: "display",
    subcategory: "monitor",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 1.50,
    repurposeIdeas: ["Status display for Arduino/Raspberry Pi projects", "Smart thermostat console", "System diagnostics screen"],
    safetyNotes: "Delicate glass layer. Avoid twisting or applying uneven pressure to the screen.",
    recyclingInfo: "Liquid crystals between glass substrates. Standard e-waste."
  },
  {
    names: ["seven segment display", "7 segment display", "led display"],
    category: "display",
    subcategory: "led",
    package: "through-hole",
    classification: "salvageable",
    desolderDifficulty: 3,
    hazards: [],
    hazardMaterials: [],
    estimatedValue: 0.40,
    repurposeIdeas: ["Digital clocks", "Scoreboards", "Voltmeters", "Industrial-looking counter displays"],
    safetyNotes: "Usually common anode or common cathode. Test with diode mode on multimeter to verify pinout.",
    recyclingInfo: "Standard LED-based display. Recyclable."
  }
];

// Helper to expand database with dynamic/derived aliases and keywords
const PREPARED_DATABASE = COMPONENT_DATABASE.map(item => {
  // Normalize search tokens
  const searchTokens = item.names.map(n => n.toLowerCase());
  return {
    name: item.names[0],
    ...item,
    searchTokens
  };
});

// Export database for browser usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = PREPARED_DATABASE;
} else {
  window.COMPONENT_DATABASE = PREPARED_DATABASE;
}
